### PR TITLE
Several fixes

### PR DESCRIPTION
**Pull request by cpuga**
Patched project controller adapted to the new API template system (index.api.rsb) & Changed form action URL from absolute to relative

### CODE REVIEW

**Comment by kikito** [comment]
Hi there!

Sorry it took me so long to answer this.

I'm under the impression that we are using different versions of redmine or chiliproject. We are using this plugin on a Chiliproject 1.x isntallation, so the "api template system" doesn't seem to be enabled on it yet. You are under 2.x, right?

I'll keep this pull request open so that I don't forget to merge it once we have updated to 2.x.

Regards,

Enrique

**Comment by cpuga** [comment]
Yes, we have redmine 1.2.1. 
Anyway, the change in the form action will make your plugin valid in all redmine/chilliproject installs, not only in those on the root directory (http:/www.redmine.com/ vs.http:// www.mydomain.com/redmine).

Best regards,
Carlos.

**Comment by kikito** [comment]
Hi again, you are absolutely right. The fix is on master now. Thanks!

**Comment by kikito** [comment]
I've merged a different pull request for the api thing. I believe this solves all the issues this pull request was solving, so I'm closing it down. Please feel free to reopen it if you don't agree.

Sorry for the time it took us to answer to this pull request - we didn't update to 2.x until very recently!

**Pull request closed without merging**
